import React, { useState } from 'react';

const DocumentGeneratorForm = ({ onGenerate, loading }) => {
  const [documentType, setDocumentType] = useState('agreement');
  const [details, setDetails] = useState('');

  const handleSubmit = e => {
    e.preventDefault();
    if (!details.trim()) return;
    onGenerate({ documentType, details });
  };

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-4 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-4 shadow-sm">
      <div className="flex flex-col gap-1">
        <label className="text-xs font-medium text-slate-600 dark:text-slate-400" htmlFor="documentType">
          Document type
        </label>
        <select
          id="documentType"
          value={documentType}
          onChange={e => setDocumentType(e.target.value)}
          className="h-9 rounded-md border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 px-2 text-sm text-slate-800 dark:text-slate-200 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
        >
          <option value="agreement">Agreement</option>
          <option value="affidavit">Affidavit</option>
          <option value="notice">Legal Notice</option>
          <option value="will">Will</option>
          <option value="nda">Non-Disclosure Agreement</option>
          <option value="custom">Custom</option>
        </select>
      </div>
      <div className="flex flex-col gap-1">
        <label className="text-xs font-medium text-slate-600 dark:text-slate-400" htmlFor="details">
          Key facts and details
        </label>
        <textarea
          id="details"
          rows={8}
          value={details}
          onChange={e => setDetails(e.target.value)}
          placeholder="Describe the parties, important dates, amounts, and any specific clauses you want to include. Do NOT paste confidential information."
          className="resize-none rounded-md border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 px-3 py-2 text-sm text-slate-800 dark:text-slate-200 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
        />
      </div>
      <div className="flex items-center justify-between gap-3">
        <p className="text-[11px] text-slate-500 dark:text-slate-400">
          Drafts are generated by AI for discussion purposes only. Always have a qualified lawyer
          review before use.
        </p>
        <button
          type="submit"
          disabled={loading || !details.trim()}
          className="inline-flex items-center rounded-md bg-primary-600 px-4 py-2 text-xs font-semibold text-white shadow-sm hover:bg-primary-500 disabled:cursor-not-allowed disabled:bg-slate-300"
        >
          {loading ? 'Generating…' : 'Generate draft'}
        </button>
      </div>
    </form>
  );
};

export default DocumentGeneratorForm;
